"""
Default PID controller parameters for Crazyflie

Based on platform_defaults.h from Crazyflie firmware
Copyright (C) 2011-2012 Bitcraze AB
"""

# Inner loop
# Attitude Rate PID parameters
PID_ROLL_RATE_KP = 200.0
PID_ROLL_RATE_KI = 400.0
PID_ROLL_RATE_KD = 2.5
PID_ROLL_RATE_KFF = 0.0 # feedforward gain (not used in the firmware)
PID_ROLL_RATE_INTEGRATION_LIMIT = 33.3

PID_PITCH_RATE_KP = 200.0
PID_PITCH_RATE_KI = 400.0
PID_PITCH_RATE_KD = 2.5
PID_PITCH_RATE_KFF = 0.0
PID_PITCH_RATE_INTEGRATION_LIMIT = 33.3

PID_YAW_RATE_KP = 120.0
PID_YAW_RATE_KI = 16.7
PID_YAW_RATE_KD = 0.0
PID_YAW_RATE_KFF = 0.0
PID_YAW_RATE_INTEGRATION_LIMIT = 166.7

# Attitude PID parameters
PID_ROLL_KP = 6.0
PID_ROLL_KI = 3.0
PID_ROLL_KD = 0.0
PID_ROLL_KFF = 0.0
PID_ROLL_INTEGRATION_LIMIT = 20.0

PID_PITCH_KP = 6.0
PID_PITCH_KI = 3.0
PID_PITCH_KD = 0.0
PID_PITCH_KFF = 0.0
PID_PITCH_INTEGRATION_LIMIT = 20.0

PID_YAW_KP = 6.0
PID_YAW_KI = 1.0
PID_YAW_KD = 0.35
PID_YAW_KFF = 0.0
PID_YAW_INTEGRATION_LIMIT = 360.0

# Outer loop
# Velocity PID parameters
PID_VEL_X_KP = 25.0
PID_VEL_X_KI = 1.0
PID_VEL_X_KD = 0.0
PID_VEL_X_KFF = 0.0

PID_VEL_Y_KP = 25.0
PID_VEL_Y_KI = 1.0
PID_VEL_Y_KD = 0.0
PID_VEL_Y_KFF = 0.0

PID_VEL_Z_KP = 25.0
PID_VEL_Z_KI = 15.0
PID_VEL_Z_KD = 0.0
PID_VEL_Z_KFF = 0.0

# Improved baro Z hold parameters (alternative)
PID_VEL_Z_KP_BARO_Z_HOLD = 3.0
PID_VEL_Z_KI_BARO_Z_HOLD = 1.0
PID_VEL_Z_KD_BARO_Z_HOLD = 1.5
PID_VEL_Z_KFF_BARO_Z_HOLD = 0.0

# Position PID parameters
PID_POS_X_KP = 2.0  
PID_POS_X_KI = 0.3
PID_POS_X_KD = 0.0
PID_POS_X_KFF = 0.0

PID_POS_Y_KP = 2.0
PID_POS_Y_KI = 0.3
PID_POS_Y_KD = 0.0
PID_POS_Y_KFF = 0.0

PID_POS_Z_KP = 3.0
PID_POS_Z_KI = 0.3
PID_POS_Z_KD = 0.0
PID_POS_Z_KFF = 0.0

# Velocity limits
PID_VEL_ROLL_MAX = 20.0
PID_VEL_PITCH_MAX = 20.0
PID_POS_VEL_X_MAX = 1.0  # m/s
PID_POS_VEL_Y_MAX = 1.0  # m/s
PID_POS_VEL_Z_MAX = 1.0  # m/s

# Thrust parameters
PID_VEL_THRUST_BASE = 35000.0
PID_VEL_THRUST_BASE_BARO_Z_HOLD = 38000.0
PID_VEL_THRUST_MIN = 20000.0

# Filter parameters
ATTITUDE_LPF_ENABLE = False
ATTITUDE_RATE_LPF_ENABLE = False
ATTITUDE_LPF_CUTOFF_FREQ = 15.0  # Hz
ATTITUDE_ROLL_RATE_LPF_CUTOFF_FREQ = 30.0  # Hz
ATTITUDE_PITCH_RATE_LPF_CUTOFF_FREQ = 30.0  # Hz
ATTITUDE_YAW_RATE_LPF_CUTOFF_FREQ = 30.0  # Hz

PID_POS_XY_FILT_ENABLE = True
PID_VEL_XY_FILT_ENABLE = True
PID_POS_XY_FILT_CUTOFF = 20.0  # Hz
PID_VEL_XY_FILT_CUTOFF = 20.0  # Hz

PID_POS_Z_FILT_ENABLE = True
PID_VEL_Z_FILT_ENABLE = True
PID_POS_Z_FILT_CUTOFF = 20.0  # Hz
PID_VEL_Z_FILT_CUTOFF = 20.0  # Hz
PID_VEL_Z_FILT_CUTOFF_BARO_Z_HOLD = 0.7  # Hz

# Yaw control
YAW_MAX_DELTA = 0.0  # If nonzero, limits yaw setpoint change rate

# Thrust limits
UINT16_MAX = 65535

# Configuration flags
CONFIG_CONTROLLER_PID_IMPROVED_BARO_Z_HOLD = False
